# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:title/

# Setup
title:               Portfolios Australia
tagline:             'Portfolio and Project Management Australia'
description:         'portfolio and project management'
url:                 http://portfoliosaustralia.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gerald Lee Jordan
  url:               https://twitter.com/geraldleejordan
  email:             jerryleejordan@gmail.com

# Custom vars
version:             1.0.0

#Added by Jerry
timezone: Pacific/Auckland
