# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:title/
relative_permalinks: true

# Setup
title:               Nocturnal Works
tagline:             'marriage counselling and resources wellington and online'
description:         'Gerald Jordan, MCouns'
url:                 http://nocturnalworks.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nocturnal Works
  url:               https://twitter.com/nocturnalworks
  email:             jerryleejordan@gmail.com

# Custom vars
version:             1.0.0

#Added by Jerry
timezone: Pacific/Auckland
